version: '3.8'

services:
  fpm:
    build:
      context: ./
      dockerfile: Dockerfile
      target: fpm

  nginx:
    depends_on:
      - fpm
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx
    ports:
      - 8888:80
